### ISSUE TITLE
Backup directory date does not reflect container timezone

### ISSUE THREAD

**Issue by malwinmp** [AronMarinelli/bitwarden-secure-sync#9]
**Settings:**
`"CronSchedule": "20 18 * * *",`

**Result (host)**
`drwxr-xr-x 2 malwin malwin 4096 Jul 31 18:20 2024-07-31T16-20-08`

**Container shell**
`root@c566a2e4261e:/app# date
Wed Jul 31 18:21:49 CEST 2024`

**Expected result:**
`2024-07-31T18-20-08`

Following code `DateTimeOffset.UtcNow.ToString("yyyy-MM-ddTHH-mm-ss")` should be replaced with timezone aware function

**Comment by AronMarinelli** [comment]
Valid point, the display time should definitely align with the configured TZ. I'll be sure to include this change in a future update.
